### ISSUE TITLE
Provide context for changes to README files in node.js

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/synthtool#651] opened 2020-06-28 05:22 UTC
Context - looking at this PR here:
https://github.com/googleapis/nodejs-dlp/pull/493

The goal is to get down to 0 `[CHANGE ME] Re-generated to pick up changes from synthtool.` PRs, so we can scale gooder.  

![image](https://user-images.githubusercontent.com/534619/85938694-6670f100-b8c4-11ea-8879-f12886fdc10d.png)

The `build: add config .gitattributes` commit was due to a change in our templated files and synthtool worked perfectly 👌 

The `changes without context` commit was due to this change:
https://github.com/googleapis/nodejs-dlp/commit/a5ec2f3baafbc770336596bdfe4737b61aba947e

When synthtool runs for node.js, there are some files are generated via template.  README is one of them!  It uses the README template in the repo, and inlines the `quickstart.js` directly in the file.  It would seem that we're not getting context for that change.

**Comment by SurferJeffAtGoogle** [comment] 2020-06-30 16:14
This is working as intended, at least according to the current design.  It's what we discussed in our good vs. perfect conversation.  Detecting this change would require rolling back changes that submitted afterwards and rebuilding, and the library, yielding a mess of confusing PRs with rollbacks that humans complained about.

It's been about 2 months since I've thought about it, so I'll think about at again and see if any new strategies come to mind.

**Comment by JustinBeckwith** [comment] 2020-06-30 21:45
This makes me wonder if we shouldn't have a higher level API available in `synthtool` to control these kinds of things.  I could see myself writing code that helps orchestrate multiple PRs in my `synth.py`:

_disclaimer: I do not know how to write python, and this is what it looks like to me when others write it_

```py
# Imagine I run the nodejs microgenerator first
synthtool.generate_node_library();

# Then I tell synthtool - hey, with the changes currently out there, scoop them up and submit a PR for me.  If I pass no params, please just figure it out using magic.
synthtool.submit_pr() 

# Now I want to do a special operation outside the generator that will edit local files
subprocess.run(['npm', 'run', 'generate-readme'])

# I want yet another PR please
synthtool.submit_pr('docs: update the README to include all libraries')
```

Alternatively, it's possible the answer here is to not use `synthtool` as a general purpose cron :) I think it's possible we've done a disservice to the tool to be entirely honest by cramming template copying, and by using it for misc cron jobs.  The answer _could_ be to use a cron job with GitHub actions for our custom workflows.  The bad news there is that we end up replicating the nice logic you have for creating PRs, opening issues on failures, and (maybe most importantly) safely injecting the github token.

**Comment by SurferJeffAtGoogle** [comment] 2020-06-30 22:04
My [new strategy](https://github.com/googleapis/synthtool/compare/master...SurferJeffAtGoogle:old-self?expand=1) is not working out.  It's generating [regressions](https://github.com/googleapis/nodejs-dlp/pull/495), just like my old strategies.  It's a fundamental issue of how git works for which I've found no work-around even with weeks of trying.

There was a two-day window between https://github.com/googleapis/nodejs-dlp/pull/492 and https://github.com/googleapis/nodejs-dlp/pull/493.  Had 492 been merged during that window, then 493 would be generated without the "changes without context" commit.  Likewise, if you merge 492 now, and then checked the box to regenerate 493, it will regenerate without the "changes without context."

So, one solution that will get rid of most, but not all of these "context: partial" commits is merging PRs ASAP.  Unfortunately, precisely because these PRs have no context, they require human review.  Maybe it can be a morning routine to review all "context: none" PRs?

**Comment by SurferJeffAtGoogle** [comment] 2020-06-30 22:16
> # Now I want to do a special operation outside the generator that will edit local files
> subprocess.run(['npm', 'run', 'generate-readme'])

I'm whatever changes this makes to the generated files will be undone the next time autosynth runs, resulting in a confusing PR.

**Comment by SurferJeffAtGoogle** [comment] 2020-09-09 16:54
Inviting @bcoe and @chingor13 to this conversation.

Assume we split generating the library source code and generating READMEs, etc. into two separate processes.  We'll still see the same number of [CHANGE ME] PRs.  Here's why:

1.  Renovate bot's https://github.com/googleapis/java-logging/pull/235 gets merged into the repo.
2.  Autosynth regenerates, finds changes in the README not triggered by any dependency, and creates https://github.com/googleapis/java-logging/pull/236/files without context.
3.  PR 236 gets a [CHANGE ME] title because there is no context.

We will still have changes triggered by recent changes to the repo itself, and Autosynth can't identify the source of those changes, so it creates a PR without context.

I have twice searched for ways that Autosynth could detect changes triggered by the self-same repo, but haven't found one.  I would love if @bcoe or @chingor13 could spend 2 hours with me thinking about the problem.  Yes, it really takes that long to define the problem and consider solutions.

**Comment by SurferJeffAtGoogle** [comment] 2020-09-16 16:36
I booked a 2-hour meeting for October 13th.

**Comment by bcoe** [comment] 2020-09-17 22:30
Sorry that I missed this, looking forward to discussing the problem.

**Comment by SurferJeffAtGoogle** [comment] 2021-05-05 23:58
I'm calling this working as intended.  Owl Bot will not suffer the same issue.

**Closed by SurferJeffAtGoogle** 2021-05-05 23:58 UTC
Labels: type: feature request
