### ISSUE TITLE
Commits from unrelated libraries are getting mixed up

### ISSUE THREAD

**Issue by Neenu1995** [googleapis/synthtool#959] opened 2021-02-23 23:21 UTC
Lately, some PRs include commits that do not belong to its repo.The commit message and description are from a random commit in an unrelated repo and the actual code change is unrelated to the commit itself. 

For example, in  [#897 in java-spanner](https://github.com/googleapis/java-spanner/pull/897) repo, one of the  [commits](https://github.com/googleapis/java-spanner/pull/897/commits/0b7cac105a5bc61f49a64b3e49b9dac396ebf831) is from a different repo, [java-channel](https://github.com/googleapis/googleapis/commit/2916ac4a35c49441baa5dc8c7e2ad5a1205ed2ca), in this example.

**Comment by SurferJeffAtGoogle** [comment] 2021-03-03 22:36
I'm having trouble making sense of this one.
I checked this box:
![image](https://user-images.githubusercontent.com/11778530/109881881-d858c180-7c2d-11eb-8133-e1bd48124f3f.png)

Let's see what the PR looks like after Autosynth runs again tonight.

**Comment by SurferJeffAtGoogle** [comment] 2021-03-09 18:30
The new autosynth run did not contain the same mistaken commit, and  thiagotnunes  merged it.

I'm closing this issue as "not reproducible."  If you see it again, please drop a note here, and check the box to automatically regenerate the PR.

**Closed by SurferJeffAtGoogle** 2021-03-09 18:30 UTC
Labels: priority: p2, type: bug

**Comment by Neenu1995** [comment] 2021-03-16 02:32
This happened again in  [#942 spanner repo](https://github.com/googleapis/java-spanner/pull/942). 
Waiting to regenerate.
