### ISSUE TITLE
Synthtool is Flip-flopping on Changes

### ISSUE THREAD

**Issue by thiagotnunes** [googleapis/synthtool#1151] opened 2021-07-13 01:48 UTC
We are using autosynth in the [java-spanner](https://github.com/googleapis/java-spanner) repository and we seem to be getting changes every now and then that undo each other. Here are some examples:

- https://github.com/googleapis/java-spanner/pull/1261
- https://github.com/googleapis/java-spanner/pull/1270
- https://github.com/googleapis/java-spanner/pull/1287

These changes come every so often, usually once a quarter.

**Comment by chingor13** [comment] 2021-07-15 04:39
@miraleung Is this being caused by the micro generator? It seems like the resource picked by the IAM samples is non-deterministic.

**Comment by chingor13** [comment] 2021-07-15 04:41
Oh, wow, it looks like we aren't even using bazel for the Spanner repo

**Comment by miraleung** [comment] 2021-07-28 04:04
Will investigate this for FixIt next week, thanks for the heads up.

**Comment by chingor13** [comment] 2021-08-16 20:48
This should be fixed now with the change to the generator.

**Closed by chingor13** 2021-08-16 20:48 UTC
Labels: type: bug, priority: p2, lang: java
