### ISSUE TITLE
Python: samples readme has outdated url

### ISSUE THREAD

**Issue by daniel-sanche** [googleapis/synthtool#867] opened 2020-12-02 18:52 UTC
The [template for the Python samples readme](https://github.com/googleapis/synthtool/blob/f94318521f63085b9ccb43d42af89f153fb39f15/synthtool/gcp/templates/python_samples/install_deps.tmpl.rst) includes references to python-docs-samples. It should be linking to the parent repo instead, as that is where samples are now stored

**Comment by parthea** [comment] 2021-08-09 19:48
I'm going to close this as a duplicate of #663 but please feel free to re-open this issue if I've misunderstood the context.

**Closed by parthea** 2021-08-09 19:48 UTC
Labels: priority: p2, samples
