### ISSUE TITLE
Python: Sphinx 3.0 raises warnings for duplicate object descriptions

### ISSUE THREAD

**Issue by busunkim96** [googleapis/synthtool#593] opened 2020-06-01 17:16 UTC
Sphinx 3.0.0 raises warnings for duplicate object descriptions. Most of our libraries have duplicate object descriptions because docstrings are added to protobuf classes via protoc-docs-plugin.

```
sphinx.errors.SphinxWarning: /tmpfs/src/github/python-monitoring/google/cloud/monitoring_v3/types.py:docstring of google.cloud.monitoring_v3.types.Aggregation.alignment_period:1:duplicate object description of google.cloud.monitoring_v3.types.Aggregation.alignment_period, other instance in gapic/v3/types, use :noindex: for one of them

Warning, treated as error:
/tmpfs/src/github/python-monitoring/google/cloud/monitoring_v3/types.py:docstring of google.cloud.monitoring_v3.types.Aggregation.alignment_period:1:duplicate object description of google.cloud.monitoring_v3.types.Aggregation.alignment_period, other instance in gapic/v3/types, use :noindex: for one of them
Command sphinx-build -W -T -N -b html -d docs/_build/doctrees/ docs/ docs/_build/html/ failed with exit code 2
```
The class object has a docstring that references the fields, and the fields themselves have generic docstrings produced by protobuf.

![image](https://user-images.githubusercontent.com/8822365/83434401-45b19a80-a3ef-11ea-91e4-fe30fe8911da.png)

https://github.com/googleapis/python-monitoring/blob/master/google/cloud/monitoring_v3/proto/alert_pb2.py

**Solutions**:

* Stop treating warnings as errors.
* Ignore this specific warning. (Unclear if this is possible)
* Use Sphinx's [Application API](https://www.sphinx-doc.org/en/master/extdev/appapi.html) to add `:noindex:` or remove the generic protobuf docstring

**Comment by parthea** [comment] 2021-08-09 19:13
I'm not able to reproduce this sphinx warning locally in python-monitoring. I've enabled sphinx warnings as errors in https://github.com/googleapis/python-monitoring/pull/196. I'm going to close this issue but please feel free to re-open it.

**Closed by parthea** 2021-08-09 19:13 UTC
Labels: type: docs
