### ISSUE TITLE
synthtool PRs do not follow conventional commits

### ISSUE THREAD

**Issue by elharo** [googleapis/synthtool#953] opened 2021-02-18 13:21 UTC
e.g. "[CHANGE ME] Re-generated to pick up changes from synthtool." in https://github.com/googleapis/google-auth-library-java/pull/574

This means every such PR fails the CI. 

Best practice is to never check in on a failing CI. If we don't care about this we should remove the conventional commits check from all repos. Otherwise we should fix this.

**Comment by busunkim96** [comment] 2021-02-25 15:48
Hi @elharo,

A PR is opened with a `CHANGE ME ...` title when Autosynth has insufficient context to determine the source. If it had enough context, it would name the PR with whatever commit triggered it. 

Options that come to mind are:

(1) Don't open the PR. This is undesirable because we miss out on changes that need to be merged.

(2) Add some conventional commit compliant placeholder. I think we don't go with this option because we _want_ the maintainer to review the changes and rename the PR appropriately.

@SurferJeffAtGoogle Could you take a look at this one?

**Comment by SurferJeffAtGoogle** [comment] 2021-02-25 16:35
@elharo When a pull request is generated with a [CHANGE ME] title, we expect the repo maintainer to investigate the pull request and re-title it.  Therefore, having the PR fail CI is actually working as intended.

I always want to learn more about how maintainers respond to these pull requests.  What's your usual course of action?

**Closed** 2021-03-09 18:31 UTC
Labels: priority: p2, type: bug
