### ISSUE TITLE
Running synthtool in nodejs-datastore causes errors

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/synthtool#735] opened 2020-08-26 03:57 UTC
With the latest synthtool, I'm seeing this call stack:

```
nodejs-datastore (master) $ python3 -m synthtool
2020-08-25 20:55:05,735 synthtool > Executing /Users/beckwith/Code/nodejs-datastore/synth.py.
Traceback (most recent call last):
  File "/Users/beckwith/Library/Python/3.6/lib/python/site-packages/google/protobuf/json_format.py", line 528, in _ConvertFieldValuePair
    [f.json_name for f in message_descriptor.fields]))
google.protobuf.json_format.ParseError: Message type "yoshi.synth.metadata.Metadata" has no field named "generatedFiles".
 Available Fields(except extensions): ['updateTime', 'sources', 'destinations', 'newFiles']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/beckwith/Library/Python/3.6/lib/python/site-packages/synthtool/__main__.py", line 102, in <module>
    main()
  File "/Users/beckwith/Library/Python/3.6/lib/python/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/beckwith/Library/Python/3.6/lib/python/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/beckwith/Library/Python/3.6/lib/python/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/beckwith/Library/Python/3.6/lib/python/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/beckwith/Library/Python/3.6/lib/python/site-packages/synthtool/__main__.py", line 93, in main
    with synthtool.metadata.MetadataTrackerAndWriter(metadata):
  File "/Users/beckwith/Library/Python/3.6/lib/python/site-packages/synthtool/metadata.py", line 173, in __enter__
    self.old_metadata = _read_or_empty(self.metadata_file_path)
  File "/Users/beckwith/Library/Python/3.6/lib/python/site-packages/synthtool/metadata.py", line 103, in _read_or_empty
    return google.protobuf.json_format.Parse(text, metadata_pb2.Metadata())
  File "/Users/beckwith/Library/Python/3.6/lib/python/site-packages/google/protobuf/json_format.py", line 434, in Parse
    return ParseDict(js, message, ignore_unknown_fields, descriptor_pool)
  File "/Users/beckwith/Library/Python/3.6/lib/python/site-packages/google/protobuf/json_format.py", line 454, in ParseDict
    parser.ConvertMessage(js_dict, message)
  File "/Users/beckwith/Library/Python/3.6/lib/python/site-packages/google/protobuf/json_format.py", line 485, in ConvertMessage
    self._ConvertFieldValuePair(value, message)
  File "/Users/beckwith/Library/Python/3.6/lib/python/site-packages/google/protobuf/json_format.py", line 596, in _ConvertFieldValuePair
    raise ParseError(str(e))
google.protobuf.json_format.ParseError: Message type "yoshi.synth.metadata.Metadata" has no field named "generatedFiles".
 Available Fields(except extensions): ['updateTime', 'sources', 'destinations', 'newFiles']
```

If I delete `synth.metadata` and run again, everything is fine.  Is it possible this is biting all our repos?

**Comment by JustinBeckwith** [comment] 2020-08-26 03:58
Making sure @bcoe and @alexander-fenster see this may be an issue...

**Comment by SurferJeffAtGoogle** [comment] 2020-08-26 16:50
Are you running this manually from the command line?

I suspect this is happening because you're running and old version of synthtool.  Please git pull the synthtool repo and try again.

**Comment by SurferJeffAtGoogle** [comment] 2020-08-26 16:51
The nightly autosynth is definitely healthy:
https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod%3Acloud-devrel%2Fclient-libraries%2Fautosynth%2Fnodejs

**Comment by JustinBeckwith** [comment] 2020-08-26 16:53
Feel free to downgrade to a P2 if we're healthy :) Just being cautious.  

I am running on the command line.  On if I'm running an old version - I followed the instructions here:
https://github.com/googleapis/synthtool/tree/master/synthtool#prerequisites

Is there a way for me to tell you what version I'm running?

**Comment by SurferJeffAtGoogle** [comment] 2020-08-26 16:56
Do a git pull, and repeat the `pip install` command in the instructions.

**Comment by JustinBeckwith** [comment] 2020-08-26 16:59
I did that, and I'm getting the same result 😭

**Comment by JustinBeckwith** [comment] 2020-08-26 17:02
Just to make sure I'm not doing something wrong:

```
synthtool (master) $ pwd
/Users/beckwith/Code/synthtool
synthtool (master) $ git fetch --all
Fetching origin
synthtool (master) $ git reset --hard origin/master
HEAD is now at 637f8aa chore(deps): update dependency protobuf to v3.13.0 (#731)
synthtool (master) $ python3 -m pip install -e .
Obtaining file:///Users/beckwith/Code/synthtool
Requirement already satisfied: click in /Users/beckwith/Library/Python/3.6/lib/python/site-packages (from gcp-synthtool==2020.2.4) (7.1.2)
Requirement already satisfied: colorlog in /Users/beckwith/Library/Python/3.6/lib/python/site-packages (from gcp-synthtool==2020.2.4) (4.1.0)
Requirement already satisfied: deprecation in /Users/beckwith/Library/Python/3.6/lib/python/site-packages (from gcp-synthtool==2020.2.4) (2.1.0)
Requirement already satisfied: jinja2 in /Users/beckwith/Library/Python/3.6/lib/python/site-packages (from gcp-synthtool==2020.2.4) (2.11.2)
Requirement already satisfied: packaging in /Users/beckwith/Library/Python/3.6/lib/python/site-packages (from gcp-synthtool==2020.2.4) (20.4)
Requirement already satisfied: PyYAML in /Users/beckwith/Library/Python/3.6/lib/python/site-packages (from gcp-synthtool==2020.2.4) (5.3.1)
Requirement already satisfied: requests in /Users/beckwith/Library/Python/3.6/lib/python/site-packages (from gcp-synthtool==2020.2.4) (2.23.0)
Requirement already satisfied: protobuf in /Users/beckwith/Library/Python/3.6/lib/python/site-packages (from gcp-synthtool==2020.2.4) (3.12.0)
Requirement already satisfied: watchdog in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from gcp-synthtool==2020.2.4) (0.10.3)
Requirement already satisfied: MarkupSafe>=0.23 in /Users/beckwith/Library/Python/3.6/lib/python/site-packages (from jinja2->gcp-synthtool==2020.2.4) (1.1.1)
Requirement already satisfied: pyparsing>=2.0.2 in /Users/beckwith/Library/Python/3.6/lib/python/site-packages (from packaging->gcp-synthtool==2020.2.4) (2.4.7)
Requirement already satisfied: six in /Users/beckwith/Library/Python/3.6/lib/python/site-packages (from packaging->gcp-synthtool==2020.2.4) (1.14.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Users/beckwith/Library/Python/3.6/lib/python/site-packages (from requests->gcp-synthtool==2020.2.4) (1.25.9)
Requirement already satisfied: idna<3,>=2.5 in /Users/beckwith/Library/Python/3.6/lib/python/site-packages (from requests->gcp-synthtool==2020.2.4) (2.9)
Requirement already satisfied: certifi>=2017.4.17 in /Users/beckwith/Library/Python/3.6/lib/python/site-packages (from requests->gcp-synthtool==2020.2.4) (2020.4.5.1)
Requirement already satisfied: chardet<4,>=3.0.2 in /Users/beckwith/Library/Python/3.6/lib/python/site-packages (from requests->gcp-synthtool==2020.2.4) (3.0.4)
Requirement already satisfied: setuptools in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from protobuf->gcp-synthtool==2020.2.4) (40.6.2)
Requirement already satisfied: pathtools>=0.1.1 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from watchdog->gcp-synthtool==2020.2.4) (0.1.2)
Installing collected packages: gcp-synthtool
  Found existing installation: gcp-synthtool 2020.2.4
    Uninstalling gcp-synthtool-2020.2.4:
      Successfully uninstalled gcp-synthtool-2020.2.4
  Running setup.py develop for gcp-synthtool
Successfully installed gcp-synthtool
You are using pip version 18.1, however version 20.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
synthtool (master) $ cd ../nodejs-datastore
nodejs-datastore (master) $ python3 -m synthtool
2020-08-26 10:01:07,111 synthtool > Executing /Users/beckwith/Code/nodejs-datastore/synth.py.
Traceback (most recent call last):
  File "/Users/beckwith/Library/Python/3.6/lib/python/site-packages/google/protobuf/json_format.py", line 528, in _ConvertFieldValuePair
    [f.json_name for f in message_descriptor.fields]))
google.protobuf.json_format.ParseError: Message type "yoshi.synth.metadata.Metadata" has no field named "generatedFiles".
 Available Fields(except extensions): ['updateTime', 'sources', 'destinations', 'newFiles']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/beckwith/Library/Python/3.6/lib/python/site-packages/synthtool/__main__.py", line 102, in <module>
    main()
  File "/Users/beckwith/Library/Python/3.6/lib/python/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/beckwith/Library/Python/3.6/lib/python/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/beckwith/Library/Python/3.6/lib/python/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/beckwith/Library/Python/3.6/lib/python/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/beckwith/Library/Python/3.6/lib/python/site-packages/synthtool/__main__.py", line 93, in main
    with synthtool.metadata.MetadataTrackerAndWriter(metadata):
  File "/Users/beckwith/Library/Python/3.6/lib/python/site-packages/synthtool/metadata.py", line 173, in __enter__
    self.old_metadata = _read_or_empty(self.metadata_file_path)
  File "/Users/beckwith/Library/Python/3.6/lib/python/site-packages/synthtool/metadata.py", line 103, in _read_or_empty
    return google.protobuf.json_format.Parse(text, metadata_pb2.Metadata())
  File "/Users/beckwith/Library/Python/3.6/lib/python/site-packages/google/protobuf/json_format.py", line 434, in Parse
    return ParseDict(js, message, ignore_unknown_fields, descriptor_pool)
  File "/Users/beckwith/Library/Python/3.6/lib/python/site-packages/google/protobuf/json_format.py", line 454, in ParseDict
    parser.ConvertMessage(js_dict, message)
  File "/Users/beckwith/Library/Python/3.6/lib/python/site-packages/google/protobuf/json_format.py", line 485, in ConvertMessage
    self._ConvertFieldValuePair(value, message)
  File "/Users/beckwith/Library/Python/3.6/lib/python/site-packages/google/protobuf/json_format.py", line 596, in _ConvertFieldValuePair
    raise ParseError(str(e))
google.protobuf.json_format.ParseError: Message type "yoshi.synth.metadata.Metadata" has no field named "generatedFiles".
 Available Fields(except extensions): ['updateTime', 'sources', 'destinations', 'newFiles']
nodejs-datastore (master) $ 
```

**Comment by alexander-fenster** [comment] 2020-08-28 02:27
@JustinBeckwith I see this sometimes and `rm -f synth.metadata` before running synthtool helps. No idea why though :)

**Comment by JustinBeckwith** [comment] 2020-08-28 02:31
Oh yeah that totally works.  I was just worried that autosynth was somehow failing on datastore generation at night.

**Comment by SurferJeffAtGoogle** [comment] 2020-09-08 23:26
@bcoe, you successfully and manually run synthtool.  What's your process?

**Comment by bcoe** [comment] 2020-09-10 18:35
@SurferJeffAtGoogle on my linux box at work, I have bazel setup,  and run `synthtool` from virtualenv. The only other special thing I've done is put environment variables in my `~/.bashrc` as needed:

```
export SYNTHTOOL_TEMPLATES=/usr/local/google/home/bencoe/google/synthtool/synthtool/gcp/templates
export SYNTHTOOL_TRACK_OBSOLETE_FILES=true
```

**Comment by JustinBeckwith** [comment] 2020-09-10 19:21
Taking 10 steps back - I think the issue here is that I have _no idea which version of synthtool I'm using_.  Until I have that, I'm just guessing at what version my machine is picking up to use.

**Comment by SurferJeffAtGoogle** [comment] 2020-09-10 19:39
>  Taking 10 steps back - I think the issue here is that I have *no idea
which version of synthtool I'm using*. Until I have that, I'm just guessing
at what version my machine is picking up to use.

Please file a bug for that issue, specifically.

**Comment by JustinBeckwith** [comment] 2020-09-10 19:47
Fair point :) If we're 100% sure autosynth is healthy, and the problem is me, please feel free to close this out!
https://github.com/googleapis/synthtool/issues/756

**Comment by SurferJeffAtGoogle** [comment] 2020-09-10 20:04
I'm 99.999% sure that autosynth is healthy, and the issue is described better in #756, so I'm closing this issue.

**Closed by SurferJeffAtGoogle** 2020-09-10 20:04 UTC
Labels: priority: p2, type: bug
